### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by andrew-scoppa** [gh-mentor/Illinoise-captions#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'Unwatch' button and selecting either the 'Participating and @mentions' or 'Ignoring' option.

**Comment by MRKnepler** [comment]
People in glasshouses should get dressed in the dark.

**Comment by andrew-scoppa** [comment]
# Add me to the list!

This is fun 😸 

- [ ] create branch
- [ ] make changes
- [ ] stage changes
- [ ] commit
- [ ] publish

[Markdown cheatsheet](https://www.markdownguide.org/cheat-sheet/)

**Comment by muzotabag** [comment]
Add me to the list,

- [ ] Create branch

**Comment by bfmonroe** [comment]
Added to the list

**Comment by Chembros123** [comment]
# Header

**This is my body**

**Comment by WallyHartshorn** [comment]
Testing. Check, check, check, check.

**Comment by IDNRMMLRD** [comment]
Commenting :)
